<?php

/**
 * Показатель "Выполнение расписания движения грузовых поездов".
 */
class TimeCargoTrain extends BaseIndicator
{
    /**
     * @var UtilsDate Объект для работы с датами.
     */
    private $utilsDate;

    /**
     * @var int Факт из ДО-25 (СИС-Эффект).
     */
    private $factDo25;

    /**
     * @var int Факт из ДО-25 прошлого года (СИС-Эффект).
     */
    private $factDo25LastYear;

    /**
     * @var int Факт из Приложения 2792 (СИС-Эффект).
     */
    private $fact2792;

    /**
     * @var int Факт из Приложения 2792 прошлого года (СИС-Эффект).
     */
    private $fact2792LastYear;

    public function __construct($codeIndicator, UtilsDate $utilsDate)
    {
        Log::Info("Формирование показателя: Выполнение расписания движения грузовых поездов");

        parent::__construct($codeIndicator);

        $this->utilsDate = $utilsDate;

        $this->getSisEffect();

        $this->iniFactLastYear();
        $this->iniPlan();
        $this->iniFact();
        $this->iniToPlanPercent();
        $this->iniToPlan();
        $this->iniToLastYearPercent();
        $this->iniToLastYear();
        $this->iniBenchmark();
    }

    /**
     * @inheritDoc
     */
    public function iniFactLastYear()
    {
        // TODO: Implement iniFactLastYear() method.
        $result = $this->factDo25LastYear == 0 ? 0 : round(($this->factDo25LastYear - $this->fact2792LastYear) / $this->factDo25LastYear * 100, 2);
        Log::Info("Факт прошлого года: {$result}");
        $this->setFactLastYear($result);
    }

    /**
     * @inheritDoc
     */
    public function iniPlan()
    {
        // TODO: Implement iniPlan() method.
        Log::Info("План: -");
        $this->setPlan("-");
    }

    /**
     * @inheritDoc
     */
    public function iniFact()
    {
        // TODO: Implement iniFact() method.
        $result = $this->factDo25 == 0 ? 0 : round(($this->factDo25 - $this->fact2792) / $this->factDo25 * 100, 2);
        Log::Info("Факт: {$result}");
        $this->setFact($result);
    }

    /**
     * @inheritDoc
     */
    public function iniBenchmark()
    {
        // TODO: Implement iniBenchmark() method.
//        $this->setBenchmark($this->getFactLastYear());
        $this->setBenchmark("пр.год за кол-во дней");
    }

    /**
     * @inheritDoc
     */
    public function iniToPlanPercent()
    {
        // TODO: Implement iniToPlanPercent() method.
        $this->setToPlanPercent("-");
    }

    /**
     * @inheritDoc
     */
    public function iniToPlan()
    {
        // TODO: Change the autogenerated stub
        $this->setToPlan("-");
    }

    /**
     * @inheritDoc
     */
    public function iniToLastYearPercent()
    {
        // TODO: Implement iniToLastYearPercent() method.
        $this->setToLastYearPercent("-");
    }

    /**
     * Выгрузка файлов из СИС-Эффект и их обработка.
     * @return void
     * @throws Exception
     */
    private function getSisEffect()
    {
        /*
         * DO25_M01.xml - СИС-Эффект / Статистическая отчетность / Хозяйство перевозок / ДО-25 / за месяц / Выполнение расписания грузовых поездов
         * DO25M11.xml - СИС-Эффект / Статистическая отчетность / Хозяйство перевозок / ДО-25 / за месяц в сравнении с пр. годом / Приложение 1 по распоряжению 2792
         */

        if ($curl = curl_init()) {
            curl_setopt($curl, CURLOPT_URL, "http://effect.gvc.oao.rzd/effect/table/DO25_M01.xml?DAT={$this->utilsDate->year}.{$this->utilsDate->month}.{$this->utilsDate->day}");
            curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($curl, CURLOPT_COOKIE, "login=smenareq;password=smenareq");
            $out = curl_exec($curl);
            file_put_contents("tmp/DO25_M01_{$this->utilsDate->year}.xml", $out);
            $this->factDo25 = 0;
            if ($out) {
                libxml_use_internal_errors(true);
                $sx = new SimpleXMLElement($out);

                $data = (array)$sx->xpath("//ss:Row");
                $rows = count($data);

                for ($row = 1; $row <= $rows; $row++) {
                    $data = (array)$sx->xpath("//ss:Row[$row]/ss:Cell[1]/ss:Data");
                    $str = $data[0][0];
//                    $nameRow = iconv("UTF-8", "windows-1251", $str);
                    $nameRow = $str;

                    if ($nameRow == "КБШ") {
                        $data = (array)$sx->xpath("//ss:Row[$row]/ss:Cell[16]/ss:Data");
                        $this->factDo25 = isset($data[0][0]) ? round($data[0][0]) : 0;
                    }
                }
            } else {
                Log::Error("Выгрузка из СИС-Эффект не произошла.");
            }
            curl_close($curl);

            if ($this->factDo25 == 0) {
                Log::Warn("Получили 0 по плану и факту, возможно есть ошибки. Проверьте файл из СИС-Эффект (tmp/DO25_M01_{$this->utilsDate->year}.xml).");
            }
        }

        if ($curl = curl_init()) {
            curl_setopt($curl, CURLOPT_URL, "http://effect.gvc.oao.rzd/effect/table/DO25_M01.xml?DAT={$this->utilsDate->lastYear}.{$this->utilsDate->monthLastYear}.{$this->utilsDate->dayLastYear}");
            curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($curl, CURLOPT_COOKIE, "login=smenareq;password=smenareq");
            $out = curl_exec($curl);
            file_put_contents("tmp/DO25_M01_{$this->utilsDate->lastYear}.xml", $out);
            $this->factDo25LastYear = 0;
            if ($out) {
                libxml_use_internal_errors(true);
                $sx = new SimpleXMLElement($out);

                $data = (array)$sx->xpath("//ss:Row");
                $rows = count($data);

                for ($row = 1; $row <= $rows; $row++) {
                    $data = (array)$sx->xpath("//ss:Row[$row]/ss:Cell[1]/ss:Data");
                    $str = $data[0][0];
//                    $nameRow = iconv("UTF-8", "windows-1251", $str);
                    $nameRow = $str;

                    if ($nameRow == "КБШ") {
                        $data = (array)$sx->xpath("//ss:Row[$row]/ss:Cell[16]/ss:Data");
                        $this->factDo25LastYear = isset($data[0][0]) ? round($data[0][0]) : 0;
                    }
                }
            } else {
                Log::Error("Выгрузка из СИС-Эффект не произошла.");
            }
            curl_close($curl);

            if ($this->factDo25LastYear == 0) {
                Log::Warn("Получили 0 по факту пр года, возможно есть ошибки. Проверьте файл из СИС-Эффект (tmp/DO25_M01_{$this->utilsDate->year}.xml).");
            }
        }

        if ($curl = curl_init()) {
            curl_setopt($curl, CURLOPT_URL, "http://effect.gvc.oao.rzd/effect/table/DO25M11.xml?DAT={$this->utilsDate->year}.{$this->utilsDate->month}.{$this->utilsDate->day}");
            curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($curl, CURLOPT_COOKIE, "login=smenareq;password=smenareq");
            $out = curl_exec($curl);
            file_put_contents("tmp/DO25M11_{$this->utilsDate->year}.xml", $out);
            $this->fact2792 = 0;
            $this->fact2792LastYear = 0;
            if ($out) {
                libxml_use_internal_errors(true);
                $sx = new SimpleXMLElement($out);

                $data = (array)$sx->xpath("//ss:Row");
                $rows = count($data);

                for ($row = 1; $row <= $rows; $row++) {
                    $data = (array)$sx->xpath("//ss:Row[$row]/ss:Cell[1]/ss:Data");
                    $str = $data[0][0];
//                    $nameRow = iconv("UTF-8", "windows-1251", $str);
                    $nameRow = $str;

                    if ($nameRow == "КБШ") {
                        $data = (array)$sx->xpath("//ss:Row[$row]/ss:Cell[3]/ss:Data");
                        $this->fact2792LastYear = isset($data[0][0]) ? round($data[0][0]) : 0;

                        $data = (array)$sx->xpath("//ss:Row[" . ($row + 1) . "]/ss:Cell[3]/ss:Data");
                        $this->fact2792 = isset($data[0][0]) ? round($data[0][0]) : 0;
                    }
                }
            } else {
                Log::Error("Выгрузка из СИС-Эффект не произошла.");
            }
            curl_close($curl);

            if ($this->fact2792 == 0 && $this->fact2792LastYear == 0) {
                Log::Warn("Получили 0 по данным из приложения 2792, возможно есть ошибки. Проверьте файл из СИС-Эффект (tmp/DO25M11_{$this->utilsDate->year}.xml).");
            }
        }
    }
}